---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blue-green-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pkupryianau/blue_green_dev
    path: blue-green-app
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: blue-green
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
