---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: blue-green
spec:
  selector:
    app: demo-app
    version: blue
  ports:
    - port: 80
      targetPort: 8088
      protocol: TCP
  type: LoadBalancer
