---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: blue-green
spec:
  selector:
    app: demo-app
    version: green
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
